import type { IGRPMenuItemArgs } from "@igrp/framework-next-types";

export const IGRP_DEFAULT_MENU: IGRPMenuItemArgs[] = [
  /*{
    id: 43,
    code: "MEU_MENU_TEST",
    name: "Meu Menu Test",
    type: "MENU_PAGE",
    position: 0,
    icon: "AppWindow",
    status: "ACTIVE",
    target: "_self",
    url: "meu-menu-test",
    pageSlug: "meu-menu-test",
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 46,
    code: "TEST_MENU_GRUPO",
    name: "Test MEnu Grupo",
    type: "FOLDER",
    position: 4,
    icon: "Folder",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 47,
    code: "TEST_PAGINA_EXTERNA",
    name: "Test Pagina Externa",
    type: "FOLDER",
    position: 0,
    icon: "AlarmClock",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 45,
    code: "TEST_MENU_EXTERNO",
    name: "Test Menu Externo",
    type: "MENU_PAGE",
    position: 3,
    icon: "ZoomIn",
    status: "ACTIVE",
    target: "_self",
    url: "test-menu-externo",
    pageSlug: "test-menu-externo",
    parentCode: "TEST_MENU_GRUPO",
    applicationCode: "APP_TEST_1",
    createdBy: "ea274d21-2386-470f-b597-9af8cbd56651",
    roles: [],
  },
  {
    id: 49,
    code: "TEST_EXTERNAL_PAGE",
    name: "Test External Page",
    type: "EXTERNAL_PAGE",
    position: 0,
    icon: "MoveUpLeft",
    status: "ACTIVE",
    target: "_blank",
    url: "https://nosi.cv",
    pageSlug: "test-external-page",
    parentCode: "TEST_PAGINA_EXTERNA",
    applicationCode: "APP_TEST_1",
    roles: [],
  },*/
  // --- SGC Essential Routes (Phase 1) ---
  {
    id: 100,
    code: "CEMETERIES",
    name: "Cemitérios",
    type: "FOLDER",
    position: 10,
    icon: "MapPin",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 105,
    code: "BLOCKS",
    name: "Blocos",
    type: "MENU_PAGE",
    position: 12,
    icon: "Layers",
    status: "ACTIVE",
    target: "_self",
    url: "blocks",
    pageSlug: "blocks",
    parentCode: "CEMETERIES",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 106,
    code: "SECTIONS",
    name: "Seções",
    type: "MENU_PAGE",
    position: 13,
    icon: "Grid",
    status: "ACTIVE",
    target: "_self",
    url: "sections",
    pageSlug: "sections",
    parentCode: "CEMETERIES",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 101,
    code: "CEMETERIES_LIST",
    name: "Listar Cemitérios",
    type: "MENU_PAGE",
    position: 11,
    icon: "List",
    status: "ACTIVE",
    target: "_self",
    url: "cemeteries",
    pageSlug: "cemeteries",
    parentCode: "CEMETERIES",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 110,
    code: "PLOTS",
    name: "Sepulturas",
    type: "FOLDER",
    position: 20,
    icon: "Layers",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 111,
    code: "PLOTS_LIST",
    name: "Listar Sepulturas",
    type: "MENU_PAGE",
    position: 21,
    icon: "Table",
    status: "ACTIVE",
    target: "_self",
    url: "plots",
    pageSlug: "plots",
    parentCode: "PLOTS",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 120,
    code: "ANALYTICS",
    name: "Análises",
    type: "FOLDER",
    position: 30,
    icon: "ChartSpline",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 121,
    code: "ANALYTICS_OCCUPANCY",
    name: "Ocupação",
    type: "MENU_PAGE",
    position: 31,
    icon: "Activity",
    status: "ACTIVE",
    target: "_self",
    url: "analytics/occupancy",
    pageSlug: "analytics-occupancy",
    parentCode: "ANALYTICS",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 130,
    code: "TOOLS",
    name: "Ferramentas",
    type: "FOLDER",
    position: 40,
    icon: "Settings2",
    status: "ACTIVE",
    target: "_self",
    url: null,
    pageSlug: null,
    parentCode: null,
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 131,
    code: "QR_CODES_GENERATE",
    name: "Gerar QR Code",
    type: "MENU_PAGE",
    position: 41,
    icon: "QrCode",
    status: "ACTIVE",
    target: "_self",
    url: "qr-codes/generate",
    pageSlug: "qr-codes-generate",
    parentCode: "TOOLS",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 132,
    code: "MAP_VIEW",
    name: "Visualizar Mapa",
    type: "MENU_PAGE",
    position: 42,
    icon: "Map",
    status: "ACTIVE",
    target: "_self",
    url: "maps",
    pageSlug: "maps",
    parentCode: "TOOLS",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  // --- Additions to align menus with existing pages ---
  {
    id: 122,
    code: "ANALYTICS_HOME",
    name: "Visão Geral",
    type: "MENU_PAGE",
    position: 30,
    icon: "ChartSpline",
    status: "ACTIVE",
    target: "_self",
    url: "analytics",
    pageSlug: "analytics",
    parentCode: "ANALYTICS",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
  {
    id: 133,
    code: "QR_CODES_REPORTS",
    name: "Relatórios QR Code",
    type: "MENU_PAGE",
    position: 43,
    icon: "FileText",
    status: "ACTIVE",
    target: "_self",
    url: "qr-codes-reports",
    pageSlug: "qr-codes-reports",
    parentCode: "TOOLS",
    applicationCode: "APP_TEST_1",
    roles: [],
  },
];
